// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbS7mzHt37MgIgXJbfK7e-JhPyg6lQagg',
    appId: '1:979242686493:web:dd59e1c4be80df976d4ef4',
    messagingSenderId: '979242686493',
    projectId: 'diet-aid-dda01',
    authDomain: 'diet-aid-dda01.firebaseapp.com',
    storageBucket: 'diet-aid-dda01.appspot.com',
    measurementId: 'G-K6V7N0M3SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrKYtdU-I1yy1rWwrJjb-4Kvgbcn36bo4',
    appId: '1:979242686493:android:4a9e5f2166ab6aae6d4ef4',
    messagingSenderId: '979242686493',
    projectId: 'diet-aid-dda01',
    storageBucket: 'diet-aid-dda01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjh3HLc3hQg2Y3-mdwgq8KSLAEQgr1xFE',
    appId: '1:979242686493:ios:2876b07b0b659f8f6d4ef4',
    messagingSenderId: '979242686493',
    projectId: 'diet-aid-dda01',
    storageBucket: 'diet-aid-dda01.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjh3HLc3hQg2Y3-mdwgq8KSLAEQgr1xFE',
    appId: '1:979242686493:ios:2876b07b0b659f8f6d4ef4',
    messagingSenderId: '979242686493',
    projectId: 'diet-aid-dda01',
    storageBucket: 'diet-aid-dda01.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbS7mzHt37MgIgXJbfK7e-JhPyg6lQagg',
    appId: '1:979242686493:web:bb05746c6b4a1a226d4ef4',
    messagingSenderId: '979242686493',
    projectId: 'diet-aid-dda01',
    authDomain: 'diet-aid-dda01.firebaseapp.com',
    storageBucket: 'diet-aid-dda01.appspot.com',
    measurementId: 'G-SC69M6ZYVE',
  );
}
