// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REVOKED_REPLACE_WITH_FIREBASE_API_KEY',
    appId: '1:457867932958:web:f19d656d08d770e691850f',
    messagingSenderId: '457867932958',
    projectId: 'fuelup-2e090',
    authDomain: 'fuelup-2e090.firebaseapp.com',
    storageBucket: 'fuelup-2e090.firebasestorage.app',
    measurementId: 'G-NBK1022TRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REVOKED_REPLACE_WITH_FIREBASE_API_KEY',
    appId: '1:457867932958:android:6e90d37d26d5539f91850f',
    messagingSenderId: '457867932958',
    projectId: 'fuelup-2e090',
    storageBucket: 'fuelup-2e090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REVOKED_REPLACE_WITH_FIREBASE_API_KEY',
    appId: '1:457867932958:ios:7ce6d06c6ef1342591850f',
    messagingSenderId: '457867932958',
    projectId: 'fuelup-2e090',
    storageBucket: 'fuelup-2e090.firebasestorage.app',
    iosBundleId: 'com.example.dietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REVOKED_REPLACE_WITH_FIREBASE_API_KEY',
    appId: '1:457867932958:ios:7ce6d06c6ef1342591850f',
    messagingSenderId: '457867932958',
    projectId: 'fuelup-2e090',
    storageBucket: 'fuelup-2e090.firebasestorage.app',
    iosBundleId: 'com.example.dietApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REVOKED_REPLACE_WITH_FIREBASE_API_KEY',
    appId: '1:457867932958:web:52b9b637f8fcb8e891850f',
    messagingSenderId: '457867932958',
    projectId: 'fuelup-2e090',
    authDomain: 'fuelup-2e090.firebaseapp.com',
    storageBucket: 'fuelup-2e090.firebasestorage.app',
    measurementId: 'G-KD5CMW1DXZ',
  );

}